version: '3.7'

services:
  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: flowers
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: flowers
      MYSQL_PASSWORD: flowers
  web:
    image: php:7.3-apache
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    links:
      - db
    environment:
      MYSQL_DATABASE: flowers
      MYSQL_USER: flowers
      MYSQL_PASSWORD: flowers
